name: j_project
type: "python:3.10"

relationships:
  database: "db:postgresql"

variables:
  env:
    DJANGO_SETTINGS_MODULE: "j_project.settings"
    PYTHONUNBUFFERED: "1"

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn j_project.wsgi:application --bind unix:$SOCKET --workers 3"
  locations:
    "/":
      passthru: true
    "/static/":
      root: "static"
      expires: 1h
      allow: true

disk: 512