name: "journalise"
type: "python:3.11"

disk: 1024

relationships:
  database: "db:postgresql"

web:
  upstream:
    socket_family: unix
  commands:
    start: "gunicorn -w 4 -b unix:$SOCKET j_project.wsgi:application"
  locations:
    "/":
      passthru: true
    "/static/":
      root: "static"
      allow: true
      expires: 1h

mounts:
  "/static":
    source: "local"
    source_path: "static"
  "/media":
    source: "local"
    source_path: "media"
