name: app

type: "python:3.10"
build:
    commands:
        - pip install -r requirements.txt

variables:
    env:
        DJANGO_SETTINGS_MODULE: j_project.settings

web:
    upstream:
        socket_family: unix
    commands:
        start: |
            gunicorn j_project.wsgi:application --bind unix:$SOCKET --workers 3 --log-file -
relationships:
    database: "db:postgresql"

mounts:
    "/static": "shared:files/static"
    "/media": "shared:files/media"